/*

Read First

*/

import { ref, get } from "firebase/database";
import { db } from "./libs/firebase/firebaseConfig";

// get the data -> load in session storage (update, delete)
window.addEventListener('DOMContentLoaded', function(e) {
    console.log(e);
});

async function pageInit() {
    const userRef = ref(db, "users/");
    const userSnapshot = await get(userRef);
    const userData = userSnapshot.val();
    // Reading data comes in as object of objects {{}, {}, {}...} NOT array of objects [{}, {}, {},...]
    // Convert:

    console.log(userData);
    console.log(Object.keys(userData));

    const users = Object.keys(userData).map(key => {
        // Set the ID generated by Mockaroo to Firebase generated ID
        userData[key].id = key;
        return userData[key];
    });
    //sessionStorage.setItem('store')
    console.log(users);

    // build out user card component (HTML + CSS)
    // Rendering component + data = UI
}

pageInit()